name: Sync LeetCode Solutions

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 執行一次
  workflow_dispatch:  # 允許手動執行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install leetcode-export

      - name: Configure LeetCode authentication
        run: |
          echo '${{ secrets.LEETCODE_COOKIES }}' > leetcode-user.json

      - name: Export LeetCode solutions
        run: |
          mkdir -p leetcode_solutions
          leetcode-export --cookies "${{ secrets.LEETCODE_COOKIES }}" --folder leetcode_solutions

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-sync LeetCode solutions" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
